### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Aarrayy** [CachyOS/wiki#50]
- [x] Improve readability
- [x] Try to correct wording in order to be more concise and clear
- [x] Create new section that covers features provided by CachyOS and obsolete some of the existing pages - #58 
- [x] Rename boot loader -> boot manager as it is the correct term when referring to UEFI systems. See: [Boot Loaders vs Boot Managers](https://www.rodsbooks.com/efi-bootloaders/principles.html) (Bottom of the page) - #53 
- [x] Rework Home Page - @Shendisx  
- [x] Improve "Why CachyOS" section - @Shendisx   #54 
- [x] Rework "What are the CachyOS repositories" section - @Shendisx   #57 
- [x] Overhaul "Installation on Root" - @Shendisx  @1Naim #61 
- [x] Small rework of "Desktop Environments" - @Shendisx  38e15d1
- [x] Move "CachyOS Applications" from PGO, BOLT and other optimization to "Why CachyOS?" - @Shendisx  264560b
- [x] Remove "Kernel Modules" from "PGO, BOLT and other optimization" - @Shendisx   264560b
- [x] Refactor "Post Install Setup" & Improve readability - @Shendisx  687a1e5
- [x] Remove "Updating CachyOS" in favor of "Post Install Setup" - @Shendisx  687a1e5
- [x] Update Kernel Manager section - @Shendisx  55b95db
- [x] Reword & Restructure "Installation Prepare" & Rename it to "Installation Preparation" - @Shendisx  #59 
- [x] Overhaul the entire sched-ext section - @Shendisx  #62 
- [ ] Add btrfs snapshots support via snapper (`cachyos-snapper-support`)
- [x] Automount external drives/partitions via fstab - #70 
- [x] Apply Plasma Settings to SDDM - @Shendisx 158e026

**Comment by azdanov** [comment]
@1Naim What should be for done `Updates for Handheld section` and `Add btrfs snapshots support via snapper (cachyos-snapper-support)`?

**Comment by 1Naim** [comment]
> Add btrfs snapshots support via snapper (cachyos-snapper-support)

I think we can just add this in post-install. I've checked the package in the past so the only step needed is to just install it.

> Updates for Handheld section

Sorry, I'm not sure.

**Comment by Anthonyn56** [comment]
Apologies if I should have made a different issue for this, but there is a bit of relevance. Also apologies if wiki does not quite reflect current status, trying to brush up before jumping into CachyOS.

I feel like there is a little bit of conflicting info in the wiki. BTRFS is suggested as default for its features. However, systemd-boot also seems default, while not supporting BTRFS features.

Assuming most modern machines are not BIOS only. I get in reality people are likely to be dual-booting, but in the situation they aren't...

https://wiki.cachyos.org/installation/boot_managers/#tldr 

> Choose GRUB if the used machine is BIOS only, pick rEFInd if planning on having multiple operating systems on the machine (Especially Windows), otherwise go with systemd-boot.

https://wiki.cachyos.org/installation/filesystem/#tldr

> Use the default filesystem BTRFS as it is considered stable and has a lot of neat features (snapshots, compression, etc).

**Comment by azdanov** [comment]
Yeah, I feel similar. Limine sounds like a good choice, but I'm not technically knowledgeable about it, so no idea if it can be recommended as a default bootloader. I use it without any issues myself for a while now.

**Comment by 1Naim** [comment]
> Assuming most modern machines are not BIOS only. I get in reality people are likely to be dual-booting, but in the situation they aren't...
> 
> https://wiki.cachyos.org/installation/boot_managers/#tldr
> 
> > Choose GRUB if the used machine is BIOS only, pick rEFInd if planning on having multiple operating systems on the machine (Especially Windows), otherwise go with systemd-boot.

That TLDR could be misleading, but FYI all boot managers support dual booting, so there's not much of an issue there.

> However, systemd-boot also seems default, while not supporting BTRFS features.

If you're talking about snapshots then yeah, we don't have an integration for it yet in systemd-boot. However, I *do* have a working [PoC](https://github.com/1Naim/kernel-install-mkinitcpio) (obviously it's incompatible with what CachyOS is using).

**Comment by Aarrayy** [comment]
Closing due to inactivity (for now)
